version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: ${CONTAINER_NAME}
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '${POSTGRES_PORT}:5432'